language: node_js

node_js:
  - 'node'
  - '10'

cache:
  directories:
    - node_modules

after_script:
  - |
    # Upload coverage to coveralls
    if [[ -f ./coverage/lcov.info ]]; then
      coveralls < ./coverage/lcov.info
    fi
